name: sysadmindb
description: This is the page for the dashboard of the system administrator.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.3
  english_words: ^4.0.0
  file_picker: ^6.2.0
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_charts: ^0.5.2
  flutter_form_builder: ^9.1.1
  flutter_html: 3.0.0-beta.2
  flutter_resizable_container: ^0.4.1
  flutter_secure_storage: ^9.0.0
  flutter_widget_from_html: ^0.14.6
  google_sign_in: ^6.1.5
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.2
  googleapis_client: ^0.0.11
  http: ^1.2.0
  intl: ^0.18.1
  mailer: ^6.0.1
  open_document: ^1.0.7
  path_provider: ^2.1.2
  pdf: ^3.10.7
  provider: ^6.0.0
  shared_preferences: ^2.1.1
  side_navigation: ^1.0.4
  syncfusion_flutter_calendar: ^24.2.7
  syncfusion_flutter_pdfviewer: ^24.2.5
  table_calendar: ^3.0.9
  universal_html: ^2.2.4
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.png
    - assets/images/loaderOld.gif
    - assets/images/dlsuccsLogo.png
    - assets/images/dlsulogo.png
    - assets/images/De_La_Salle_University_Seal.png
flutter_intl:
  enabled: true
