name: sysadmindb
description: This is the page for the dashboard of the system administrator. 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

  side_navigation: ^1.0.4
  firebase_core: ^2.16.0
  google_sign_in: ^6.1.5
  firebase_auth: ^4.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.png

