name: sysadmindb
description: This is the page for the dashboard of the system administrator.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  appflowy_board: ^0.1.1
  cloud_firestore: ^4.9.3
  english_words: ^4.0.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.16.0
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_charts: ^0.5.2
  flutter_form_builder: ^9.1.1
  google_sign_in: ^6.1.5
  http: ^1.2.0
  intl: ^0.18.1
  kanban_board: ^0.1.0
  mailer: ^6.0.1
  open_document: ^1.0.7
  path_provider: ^2.1.2
  pdf: ^3.10.7
  provider: ^6.0.0
  shared_preferences: ^2.1.1
  side_navigation: ^1.0.4
  syncfusion_flutter_pdfviewer: ^24.2.5
  universal_html: ^2.2.4
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.png
    - assets/images/loaderOld.gif
    - assets/pdfs/RoxasResume.pdf
    - assets/images/dlsuccsLogo.png
    - assets/images/dlsulogo.png
