// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSlgQMbCN9vZo3nA7RsaQlkeKDAnRVevc',
    appId: '1:703443900752:web:0efc3bc370b70f7c8b3455',
    messagingSenderId: '703443900752',
    projectId: 'gstrackingsys',
    authDomain: 'gstrackingsys.firebaseapp.com',
    storageBucket: 'gstrackingsys.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB40NJsrUqxUP0vuW5va8QGnrC279q6P1Y',
    appId: '1:703443900752:android:82e9634eed833ae18b3455',
    messagingSenderId: '703443900752',
    projectId: 'gstrackingsys',
    storageBucket: 'gstrackingsys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG-b3qqNkkzc3wGG1ckZqHROU7lQ_XL0M',
    appId: '1:703443900752:ios:851c5d52d2bed75f8b3455',
    messagingSenderId: '703443900752',
    projectId: 'gstrackingsys',
    storageBucket: 'gstrackingsys.appspot.com',
    iosBundleId: 'com.example.sysadmindb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG-b3qqNkkzc3wGG1ckZqHROU7lQ_XL0M',
    appId: '1:703443900752:ios:8d9d4ea59a1f05f98b3455',
    messagingSenderId: '703443900752',
    projectId: 'gstrackingsys',
    storageBucket: 'gstrackingsys.appspot.com',
    iosBundleId: 'com.example.sysadmindb.RunnerTests',
  );
}
